[project]
name = "bluejet"
version = "0.1.1"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "bluejetgh", email = "bluejetgh@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.5.3",
    "torch>=2.14.0",
]

[tool.maturin]
module-name = "bluejet._core"
python-packages = ["bluejet"]
python-source = "src"

[tool.uv]
cache-keys = [{ file = "pyproject.toml" }, { file = "src/**/*.rs" }, { file = "Cargo.toml" }, { file = "Cargo.lock" }]

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"
